#!/usr/bin/env python3
"""
evolution-kit 夜间三省检查脚本
需要安装的依赖: 内置模块即可

输出: 分析报告打印到 stdout
"""

import json
import os
import re
from datetime import datetime, date
from pathlib import Path


EVO_DIR = Path.home() / ".openclaw" / "evolution_workspace" / "ai_evolution_chamber"
LOGS_DIR = EVO_DIR / "logs"
KNOWLEDGE_DIR = EVO_DIR / "knowledge"
RULES_DIR = EVO_DIR / "rules"
STATE_FILE = EVO_DIR / "nightly_state.json"
REPORT_FILE = EVO_DIR / "nightly_report.md"


def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"last_run": None, "consecutive_no_issues": 0}


def save_state(state: dict):
    STATE_FILE.write_text(json.dumps(state, indent=2, ensure_ascii=False))


def today_log() -> str:
    today = date.today()
    for f in sorted(LOGS_DIR.glob("*.md"), reverse=True):
        if str(today) in f.stem:
            return f.read_text(encoding="utf-8")
    return ""


def extract_errors(text: str) -> list[dict]:
    errors = []
    for line in text.split("\n"):
        if re.search(r"❌|Error|失败|crash|failed", line, re.IGNORECASE):
            errors.append({"line": line.strip(), "type": "error"})
    return errors


def extract_patterns(text: str) -> list[str]:
    patterns = re.findall(r"(bug|修复|待办|todo|lesson|教训|复盘|反思)[：:].*", text, re.IGNORECASE)
    return patterns


def check_rules() -> list[str]:
    """检查 rules 目录，是否存在已解决的问题模式未收录"""
    issues = []
    existing_rules = set()
    for f in RULES_DIR.glob("*.md"):
        existing_rules.add(f.stem.lower())

    # 这里可以扩展为动态模板匹配
    return issues


def main():
    now = datetime.now()
    state = load_state()

    print(f"🌙 夜间三省检查 — {now.strftime('%Y-%m-%d %H:%M')}")
    print(f"   工作空间: {EVO_DIR}")

    # 1. 日志回顾
    log = today_log()
    if not log:
        print("   ⚠️ 未找到今日日志")
        report("未找到今日日志，跳过检查。")
        state["last_run"] = now.isoformat()
        save_state(state)
        return

    print(f"   📋 日志长度: {len(log)} 字符")

    # 2. 错误提取
    errors = extract_errors(log)
    patterns = extract_patterns(log)

    report_lines = []
    for err in errors:
        report_lines.append(f"- ❌ {err['line']}")
    for p in patterns:
        report_lines.append(f"- 💡 {p}")

    # 3. 规则建议
    rule_issues = check_rules()
    for ri in rule_issues:
        report_lines.append(f"- 📐 {ri}")

    # 4. 写入报告
    report_text = (
        f"# 夜间三省报告\n"
        f"时间: {now.isoformat()}\n"
        f"检查项: 日志回顾 | 错误提取 | 模式发现 | 规则建议\n\n"
        f"## 错误\n"
        + ("\n".join([f"- ❌ {e['line']}" for e in errors[:10]]) or "无\n") +
        f"\n## 模式\n"
        + ("\n".join([f"- 💡 {p}" for p in patterns[:10]]) or "无\n") +
        f"\n## 建议\n"
        + ("\n".join(rule_issues) or "无\n") +
        f"\n---\n_Generated by nightly_check.py_\n"
    )
    REPORT_FILE.write_text(report_text, encoding="utf-8")
    print(f"   📝 报告已写入: {REPORT_FILE}")

    state["last_run"] = now.isoformat()
    save_state(state)
    print(" ✅ 夜间三省检查完成")


def report(msg: str):
    REPORT_FILE.write_text(f"# 夜间三省报告\n时间: {datetime.now().isoformat()}\n\n{msg}\n",
                           encoding="utf-8")


if __name__ == "__main__":
    main()
